core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('file_server.urls')),
]

file_server/urls.py
from django.urls import path, re_path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'file_server'

urlpatterns = [
    path('', views.index, name='index'),
    path('upload-file', views.upload_file, name='upload_file'),
    path('delete/files/<int:file_id>', views.delete_file, name='delete_file'),
    path('sign-in', views.sign_in, name='login'),
    path('sign-out', views.sign_out, name='logout'),
    path('sign-up', views.sign_up, name='signup'),
    re_path(r'media/*', views.protected_serve, {'document_root': settings.MEDIA_ROOT})
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

file_server/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

def upload_path(instance, filename):
    return f'files/{instance.user.id}/{filename}'

class File(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=100, blank=True)
    file = models.FileField(upload_to=upload_path)
    uploaded_at = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.name
    

    def save(self, *args, **kwargs):
        if self.file:
            self.name = self.file.name
        super().save(*args, **kwargs)

file_server/forms.py
from django.forms import ModelForm

from .models import File

class FileForm(ModelForm):
    class Meta:
        model = File
        fields = ['file']

file_server/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.views.static import serve
from django.contrib import messages

from .models import File
from .forms import FileForm

# Create your views here.
def index(request):
    if request.user.is_authenticated:
        files = File.objects.filter(user=request.user)
        return render(request, 'file_server/index.html', {'files': files})
    return render(request, 'file_server/index.html')


@login_required(login_url='file_server:login')
def protected_serve(request, document_root=None):
    if request.user.is_authenticated:
        path_arr = request.path.split('/')
        print(path_arr)
        if len(path_arr) >= 2:
            try:
                file_index = path_arr.index('files')
                user_id = path_arr[file_index + 1]
                if user_id != str(request.user.id):
                    message = 'You are not authorized to view this file'
                    messages.info(request, message)
                    return redirect('file_server:index')
            except:
                message = 'Something went wrong'
                messages.info(request, message)
                return redirect('file_server:index')

        request.path = request.path.replace('/media', '')

        return serve(request, request.path, document_root)
    else:
        message = 'You are not logged in'
        messages.info(request, message)
        return redirect('file_server:login')
    

@login_required(login_url='file_server:login')
def upload_file(request):
    if request.method == 'POST':
        form = FileForm(request.POST, request.FILES)
        print(form.data)
        if form.is_valid():
            file_obj = form.save(commit=False)
            file_obj.user = request.user
            file_obj.save()
            return redirect('file_server:index')
        else:
            msgs = form.errors
            for msg in msgs:
                message = msgs[msg][0]
            messages.info(request, message)
            return render(request, 'file_server/upload_file.html')

    return render(request, 'file_server/upload_file.html', {'form': FileForm()})


@login_required(login_url='file_server:login')
def delete_file(request, file_id):
    try:
        file = File.objects.get(id=file_id)
    except:
        message = 'File does not exist'
        messages.info(request, message)
        return redirect('file_server:index')
    if file.user == request.user:
        file.delete()
        return redirect('file_server:index')
    else:
        message = 'You are not authorized to delete this file'
        messages.info(request, message)
        return redirect('file_server:index')


def sign_in(request):
    form = AuthenticationForm()
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            user = authenticate(request, username=form.cleaned_data['username'], password=form.cleaned_data['password'])

            if user is not None:
                login(request, user)
                if request.GET.get('next'):
                    return redirect(request.GET.get('next'))
                return redirect('file_server:index')
        else:
            message = 'Invalid username or password'
            messages.info(request, message)
            return render(request, 'file_server/sign_in.html')
        
    elif request.method == 'GET':
        if request.user.is_authenticated:
            return redirect('file_server:index')
        return render(request, 'file_server/sign_in.html')
    # return render(request, 'file_server/sign_in.html')


def sign_up(request):
    form = UserCreationForm()

    if request.method == 'POST':
        form = UserCreationForm(request.POST)

        if form.is_valid():
            # save user
            user = form.save()
            # login user
            login(request, user)
            return redirect('file_server:index')
        else:
            msgs = form.errors
            for msg in msgs:
                message = msgs[msg][0]
                print(message, type(message))
            # messages.info(request, message)
            return render(request, 'file_server/sign_up.html', {'form': form})
        
    elif request.method == 'GET':
        if request.user.is_authenticated:
            return redirect('file_server:index')
        return render(request, 'file_server/sign_up.html', {'form': form})


def sign_out(request):
    logout(request)
    return redirect('file_server:index')
    # return render(request, 'file_server/index.html')

file_server/templates/file_server/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>File server</title>

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
</head>
<body>
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg bg-body-tertiary px-5">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'file_server:index' %}">File Server</a>
      </div>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          {% if not request.user.is_authenticated %}
            <a class="nav-link active" areia-current="page" href="{% url 'file_server:signup' %}">Signup</a>
            <a class="nav-link active" areia-current="page" href="{% url 'file_server:login' %}">Login</a>
          {% else %}
            <span class="nav-link active" areia-current="page">{{ request.user|upper }}</span>
            <a class="nav-link active" areia-current="page" href="{% url 'file_server:logout' %}">Logout</a>
          {% endif %}
        </div>
      </div>
    </nav>

    <!-- Content -->
    <div class="container">
        {% block content %}
        {% endblock content %}
    </div>
    
    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>

    <!-- Scripts -->
    {% block scripts %}
    {% endblock scripts %}
</body>
</html>

file_server/templates/file_server/index.html
{% extends 'file_server/base.html' %}

{% block content %}
{% if request.user.is_authenticated %}
    {% for message in messages %}
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            <strong>{{ message }}</strong>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endfor %}


    <div class="containter my-5">
        <div class="row">
            <div class="col-md-12 text-center">
                <h3>Your Files</h3>
            </div>
        </div>
        {% for file in files %}
            <div class="row">
                <div class="col-md-12 d-flex justify-content-between border rounded py-2 px-4 g-2">
                    <a class="btn text-primary" href="{{ file.file.url }}">{{ file.name }}</a>
                    <a class="btn text-danger" href="{% url 'file_server:delete_file' file.id %}">Delete</a>
                </div>
            </div>
        {% endfor %}
        <a class="p-2 mt-4 border btn btn-primary" href="{% url 'file_server:upload_file' %}">Upload new file</a>
    </div>

{% else %}
    <div class="my-4">
        <h1 class="text-center">Welcome to File Server!</h1>
    
        <div class="mt-3">
            <p class="text-center">Please <a href="{% url 'file_server:login' %}">login</a> to see your files.</p>
            <p class="text-center">If you don't have an account, you can</p>
            <p class="text-center">Please <a href="{% url 'file_server:signup' %}">sign up</a> to create an account.</p>
        </div>
    </div>
{% endif %}
{% endblock content %}

{% block scripts %}
    
{% endblock scripts %}

file_server/templates/file_server/sign_in.html
{% extends 'file_server/base.html' %}
{% block content %}
    {% for message in messages %}
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            <strong>{{ message }}</strong>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endfor %}
    
    <div class="my-5">
        <h2 class="text-center">Login</h2>
        <form action="{% url 'file_server:login' %}?next={{request.GET.next}}" method="post">
            {% csrf_token %}
            <div class="mb-3">
              <label for="id_username" class="form-label">Username</label>
              <input type="text" class="form-control" id="id_username" name="username" autofocus="" autocapitalize="none" autocomplete="username" maxlength="150" required="">
            </div>
            <div class="mb-3">
              <label for="id_password" class="form-label">Password</label>
              <input type="password" name="password" class="form-control" id="id_password" autocomplete="current-password" name="password", required>
            </div>
            <button type="submit" class="btn btn-primary">Login</button>
          </form>
    </div>
{% endblock content %}

file_server/templates/file_server/sign_up.html
{% extends 'file_server/base.html' %}

{% block content %}
    {% for message in messages %}
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            <strong>{{ message }}</strong>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endfor %}

    <h2 class="text-center my-5">Sign Up</h2>
    <form action="" method="post">
        {% csrf_token %}
        <div class="mb-3">
            <label for="id_username" class="form-label">Username</label>
            <input type="text" class="form-control" id="id_username" name="username" autofocus="" autocapitalize="none" autocomplete="username" maxlength="150" required="">
        </div>
        <div class="mb-3">
            <label for="id_password1" class="form-label">Password</label>
            <input type="password" name="password1" class="form-control" id="id_password1" autocomplete="new-password" name="password", required>
        </div>
        <div class="mb-3">
            <label for="id_password2" class="form-label">Password Confirmation</label>
            <input type="password" name="password2" class="form-control" id="id_password2" autocomplete="new-password" name="password", required>
        </div>
        <button type="submit" class="btn btn-primary">Login</button>

    </form>
{% endblock %}

file_server/templates/file_server/upload_file.html
{% extends 'file_server/base.html' %}
{% load static %}
{% block content %}
    {% for message in messages %}
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            <strong>{{ message }}</strong>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endfor %}


        <h2 class="text-center">Upload a file</h2>

    <form action="" method="post" enctype="multipart/form-data" id="upload-form">
        {% csrf_token %}
        
        <div class="mb-3">
            <label for="formFile" class="form-label">Select a file</label>
            <input class="form-control" name="file" type="file" id="formFile" required>
        </div>

        <button type="submit" class="btn btn-primary">Upload</button>
    </form>

    <div class="not-visible mt-5" id="progress">
    </div>
{% endblock content %}

{% block scripts %}
    <script src="{% static 'js/handleUpload.js' %}"></script>
{% endblock scripts %}